package ma.fstt.ihm;

import javax.swing.*;
import java.awt.*;

public class BusEdit extends JFrame {
    private JPanel busEditPanel;

    public BusEdit(Integer tempBus) {

        setContentPane(busEditPanel);
        setTitle("Modifier Bus");
        setSize(500, 800);
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        busEditPanel = new JPanel();
        busEditPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return busEditPanel;
    }
}
