package ma.fstt.ihm;

import javax.swing.*;
import java.awt.*;

public class CammionEdit extends JFrame {
    private JPanel cammionEditPanel;

    public CammionEdit(Integer tempCammion) {
        setContentPane(cammionEditPanel);
        setTitle("Modifier Cammion");
        setSize(500, 800);
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        cammionEditPanel = new JPanel();
        cammionEditPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return cammionEditPanel;
    }
}
