package ma.fstt.ihm;

import javax.swing.*;
import java.awt.*;

public class MissionEdit extends JFrame {
    private JPanel missionEditPanel;

    public MissionEdit(Integer tempMission) {
        setContentPane(missionEditPanel);
        setTitle("Modifier Mission");
        setSize(500, 800);
        setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        missionEditPanel = new JPanel();
        missionEditPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return missionEditPanel;
    }
}
